model_type: conditional_il_model

output_dir: data/imitation_learning/experiments/local_test
train_path: data/imitation_learning/preprocessed/TRAIN*.tfrecord.gz
validation_path: data/imitation_learning/preprocessed/VAL*.tfrecord.gz

# Edited learning rate : 0.0002 -> 0.0001 / batch_size : 120 -> 60
train_steps: 450000
train_batch_size: 64
save_checkpoints_steps: 10000
eval_batch_size: 64

# Hyperparameters
learning_rate: 0.0002
shuffle_buffer_size: 10000
save_summary_steps: 500
lambda_steer: 14.29
lambda_gas: 1.666
lambda_brake: 1.666
lambda_speed: 0.00001
